name: Lint commit messages
on:
  push:
    branches:
      - main
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3.5.0
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@4feee87144cedc9ebed8854b383a61dafc51ebf9 # tag=v5.2.0
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
