name: Lint commit messages
on:
  push:
    branches:
      - main
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3.3.0
        with:
          node-version: 14
      - name: Install project
        run: npm ci --ignore-scripts
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@dc3881d2d829bab499b3ad5ed9937ed1bb5860e0 # tag=v5.0.1
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
