name: Lint commit messages
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@9f3ee308d1054ab5795a001773c08b55ea71473f # tag=v1.3.0
    with:
      configFile: package.json
